title: Box Critters Modding Community
description: Install mods and other add-ons to Box Critters
base-url: ""
url: https://boxcrittersmods.ga
repository: boxcritters/boxcrittersmods.ga
bc-mod-api: api.boxcrittersmods.ga
show-mod-versions: true
collections:
  authors:
    output: true
    title: Authors
    singular: Author
  shaders:
    output: true
    title: Shaders
    singular: Shader
  servers:
    output: true
    title: Servers
    singular: Server
  other:
    output: true
    title: Other
    singular: Other
  mods:
    output: true
    title: Mods
    singular: Mod
  posts:
    output: true
    title: Blog
    singular: Post
  lists:
    output: true
    title: Lists
    singular: List
    permalink: /:name/
  projects:
    output: true
    title: Projects
    singular: Project
  texturepacks:
    output: true
    title: Texture Packs
    singular: Texture Pack
permalink: pretty
production: true
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mention
markdown: kramdown
theme: minima
kramdown:
  math-engine: mathjax
  auto_ids: false
  input: GFM
  entity-output: as_char
  footnote-nr: "1"
  toc-levels: 1..6
  gfm-quirks: paragraph_end
  syntax-highlighter-opts:
    default-lang: plaintext
  syntax-highlighter: rouge
  smart-quotes: lsquo,rsquo,ldquo,rdquo
excludes:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - "*.sh"
  - README.md
  - gulffile.js
  - package.json
  - vendor
  - .gitignore
  - CNAME
  - icomoon-selection.json
defaults:
  - scope:
      path: ""
    values:
      layout: item
      featured: false
      maincard: true
      list: false
      filters: []
      home: 0
      show-nav: true
      comments: true
  - scope:
      path: ""
      type: lists
    values:
      maincard: false
      list: true
      comments: false
  - scope:
      path: ""
      type: authors
    values:
      list: documents
      filters:
        - type: match
          properties:
            - "{{item.author}}"
            - "{{page.title}}"
        - type: match
          not: true
          properties:
            - "{{page.hideCredit}}"
            - "{{item.title}}"
  - scope:
      path: ""
      type: posts
    values: {}
  - scope:
      path: ""
      type: texturepacks
    values:
      require:
        - texture-pack-manager
  - scope:
      path: ""
      type: shaders
    values:
      require:
        - boxcritters-shaders
        - texture-pack-manager
