---
layout: null
---
backend:
  name: github
  repo: {{site.repository}}
  base_url: https://{{site.bc-mod-api}}
local: "en"
media_folder: "uploads"
show_preview_links: true
publish_mode: editorial_workflow
site_url: {{site.url}}
display_url: {{site.url}}
logo_url: {{site.url}}/uploads/logo.png
collections:{% for type in site.collections %}{% assign normalTitle=type.label|capitalize %}
  - name: "{{ type.label }}"
    label: "{{type.title|default:normalTitle}}"
    label_singular: "{{type.singular|default:normalTitle }}"
    media_folder: "/uploads/{{type.label }}/"
    folder: _{{type.label }}
    create: true
    preview_path: /{{type.label}}/{{ "{{ slug "}}}}
    fields:
      - {label: "Title", name: "title", widget: "string", required: false}
      - label: "Author"
        name: "author"
        widget: "select"
        required: false
        multiple: true
        options: [{{site.authors|map:"title"|join:","}}]
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Disclamer", name: "disclaimer", widget: "text", required: false}
      - {label: "Date", name: "date", widget: "datetime", required: false}
      - {label: "Logo", name: "logo", widget: "image", required: false}
      - {label: "Banner", name: "image", widget: "image", required: false}
      - {label: "Texture Pack Code", name: "code", widget: "text", required: false}
      - {label: "Unfinished", name: "unfinished", widget: "boolean", required: false }
      - label: "Buttons"
        name: "buttons"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "URL", name: "href", widget: "string", required: false}
          - {label: "Color", name: "color", widget: "string", required: false}
          - {label: "Image", name: "image", widget: "image", required: false}
          - label: "Browser"
            name: "browser"
            widget: "select"
            required: false
            multiple: false
            options: [chrome,firefox,edge,safari,opera,ios,android]
          - label: "Type"
            name: "type"
            widget: "select"
            default: 0
            options:
            - { label: "Manual", value: -1 }
            - { label: "Primary", value: 0 }
            - { label: "Secondary", value: 1 }
          - {label: "Class", name: "style", widget: "string", required: false}
          - {label: "Style", name: "style", widget: "text", required: false}
      - {label: "Show on Front Page", name: "featured", widget: "boolean", required: false}
      - {label: "Is a Userscript", name: "userscript", widget: "boolean", required: false}
      - label: "Dependecies"
        name: "require"
        widget: "select"
        required: false
        multiple: true
        options: [{{site.mods|map:"slug"|join:","}}]
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Recommend", name: "recommend", widget: "boolean", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}{% endfor %}
  - label: "Settings"
    name: "settings"
    files:
      - label: "site"
        name: "site"
        file: "_config.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Base URL", name: "base-url", widget: "string", required: false}
          - {label: "URL", name: "url", widget: "string", required: false}
          - {label: "Repo", name: "repository", widget: "string", required: false}
          - {label: "API", name: "bc-mod-api", widget: "string", required: false}
          - {label: "Show Mod Versions", name: "show-mod-versions", widget: "boolean", required: false}
          - label: "Collections"
            name: collections
            widget: "object"
            fields:{% for type in site.collections %}{% assign normalTitle=type.label|capitalize %}
              - label: "{{type.title|default:normalTitle}}"
                name: {{type.label}}
                widget: "object"
                fields:
                  - {label: "Title", name: "title", widget: "string", required: false}
                  - {label: "Singular", name: "singular", widget: "string", required: false}
                  - {label: "URL", name: "url", widget: "string", required: false,default:"/{{type.label}}"}
                  - {label: "Home", name: "home", widget: "boolean", required: false}
                  - {label: "Output", name: "output", widget: "boolean", required: false}{% endfor %}
          - label: "Permalink"
            name: "permalink"
            widget: "select"
            required: false
            options: [date,pretty,ordinal,weekdate,none]
          - {label: "Production", name: "production", widget: "boolean", required: false}
          - label: "Plugins"
            name: "plugins"
            widget: "list"
          - label: "Markdown"
            name: "markdown"
            widget: "select"
            required: false
            options: [kramdown]
          - label: "Theme"
            name: "theme"
            widget: "select"
            required: false
            options: [minima]
          - label: "Kramdown"
            name: kramdown
            widget: "object"
            fields:
            - {label: "Auto IDs", name: "auto-ids", widget: "boolean", required: false}
            - {label: "Entity output", name: "entity-output", widget: "string", required: false}
            - {label: "Footnote starting Number", name: "footnote-nr", widget: "string", required: false}
            - {label: "GitHub MD Quirks", name: "gfm-quirks", widget: "string", required: false}
            - {label: "Hard Wrap", name: "hard-wrap", widget: "boolean", required: false}
            - {label: "MD Type", name: "input", widget: "string", required: false}
            - {label: "Math engine", name: "math-engine", widget: "string", required: false}
            - {label: "Show Warnings", name: "show-warnings", widget: "boolean", required: false}
            - {label: "Smart Quotes", name: "smart-quotes", widget: "string", required: false}
            - {label: "Syntax Highlighter", name: "syntax-highlighter", widget: "string", required: false}
            - label: "Syntax Highlighter Options"
              name: syntax-highlighter-opts
              widget: "object"
              fields:
                - {label: "Default Language", name: "default-lang", widget: "string", required: false}
            - {label: "Template", name: "template", widget: "string", required: false}
            - {label: "Table of Contents Levels", name: "toc-levels", widget: "string", required: false}
          - label: "Excludes"
            name: "excludes"
            widget: "list"
          - label: "Defaults"
            name: "defaults"
            widget: "list"
            fields:
              - label: "Scope"
                name: scope
                widget: "object"
                fields:
                - {label: "Path", name: "path", widget: "string", required: false}
                - label: "Type"
                  name: "type"
                  widget: "select"
                  required: false
                  options: [{{site.collections|map:"label"|join:","}},]
              - label: "Values"
                name: values
                widget: "object"
                fields:
                - {label: "Comments", name: "comments", widget: "boolean", required: false}
                - {label: "List", name: "list", widget: "boolean", required: false}
                - {label: "Show Nav", name: "show-nav", widget: "boolean", required: false}
                - label: "Dependecies"
                  name: "require"
                  widget: "select"
                  required: false
                  multiple: true
                  options: [{{site.mods|map:"slug"|join:","}}]
      - label: "Menus"
        name: "menus"
        file: "_data/menus.yml"
        fields:{% assign menus = "nav,user,mobile"|split:"," %}{% for m in menus %}
          - label: "{{m|capitalize}}"
            name: {{m}}
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string", required: false}
              - {label: "URL", name: "href", widget: "string", required: false}{% if m=="mobile" %}
              - {label: "Icon", name: "icon", widget: "string", required: false}{% endif %}{% if m=="nav" %}
              - {label: "Color", name: "color", widget: "string", required: false}{% endif %}{% endfor %} 
      - label: "Admin CMS"
        name: "admin"
        file: "_data/page"
        fields:
          - {label: "Enable Drafts", name: "drafts", widget: "boolean", required: false}
          - {label: "Enable Preview", name: "preview", widget: "boolean", required: false}
          - label: "Widgets"
            name: "Widgets"
            widget: "list"{% if site.data.admin.widgets %}
            field: {% include admin/field.yml name="name" %}
          - label: "Item Properties"
            name: "items"
            widget: "list"
            required: false
            fields:
              - {% include admin/field.yml name="name" %}
              - {% include admin/field.yml name="label" %}
              - label: "Widget"
                name: "widget"
                widget: "select"
                required: false
                multiple: true
                default: "text"
                options: [{{site.data.admin.widgets|join:","}}]
              - {% include admin/field.yml name="default" %}
              - {% include admin/field.yml name="multiple" widget="boolean" %}
              - label: "Options"
                name: "options"
                widget: "list"
                fields:
                  - {% include admin/field.yml name="label" %}
                  - {% include admin/field.yml name="value" %}
              - label: "Field(s)"
                name: "fields"
                widget: "list"
                fields:
                - {% include admin/field.yml name="name" %}
                - {% include admin/field.yml name="field" %}
                - label: "Widget"
                  name: "widget"
                  widget: "select"
                  required: false
                  multiple: true
                  default: "text"
                  options: [{{site.data.admin.widgets|join:","}}]
                {% include admin/field.yml name="multiple" widget="boolean" %}
                - label: "Options"
                  name: "options"
                  widget: "list"
                  fields:
                    - {% include admin/field.yml name="label" %}
                    - {% include admin/field.yml name="value" %}
                {% endif %}