backend:
  name: github
  repo: boxcritters/boxcritters.github.io
  base_url: https://bc-mod-api.herokuapp.com
media_folder: "uploads"
show_preview_links: true
logo_url: http://boxcritters.github.io/uploads/logo.png
collections:
  - name: 'texturepacks'
    label: Texture Packs
    label_singular: Texture Pack
    media_folder: "media/texturepacks/"
    folder: _texturepacks
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - label: "Authors"
        name: "author"
        widget: "list"
        field: {label: Author, name: author, widget: "string", required: true}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Date", name: "date", widget: "date", required: true}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Banner", name: "image", widget: "image"}
      - {label: "Texture Pack Code", name: "code", widget: "text", required: true}
      - {label: "One Click File", name: "install", widget: "string"}
      - {label: "Show on Front Page", name: "featured", widget: "boolean", required: false}
  - name: 'mods'
    label: Mods
    label_singular: Mod
    media_folder: "media/mods/"
    folder: _mods
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Author", name: author, widget: "string", required: true }
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Date", name: "date", widget: "date", required: true}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Banner", name: "image", widget: "image"}
      - label: "Platforms"
        name: "platforms"
        widget: "select"
        required: true
        multiple: true
        options:
          - { label: "Chrome", value: "chrome" }
          - { label: "Firefox", value: "firefox" }
          - { label: "Edge", value: "edge" }
          - { label: "Safari", value: "safari" }
          - { label: "Opera", value: "opera" }
      - {label: "Install URL", name: "install", widget: "string", required: true}
      - {label: "Show on Front Page", name: "featured", widget: "boolean", required: false}
  - name: 'tools'
    label: Tools
    label_singular: Tool
    media_folder: "media/tools/"
    folder: _tools
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Author", name: author, widget: "string" }
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Date", name: "date", widget: "date", required: true}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Banner", name: "image", widget: "image"}
      - label: "Platforms"
        name: "platforms"
        widget: "object"
        fields:
        - label: "Platform Name"
          name: "name"
          widget: "select"
          required: true
          options:
            - { label: "Chrome", value: "chrome" }
            - { label: "Firefox", value: "firefox" }
            - { label: "Edge", value: "edge" }
            - { label: "Safari", value: "safari" }
            - { label: "Opera", value: "opera" }
            - { label: "iOS", value: "ios" }
            - { label: "Android", value: "android" }
        - {label: "URL", name: "install", widget: "string", required: true}
      - {label: "Show on Front Page", name: "featured", widget: "boolean", required: false}
  - name: "posts"
    label: "Blog"
    folder: "/_posts/"
    label_singular: Blog Post
    media_folder: "media/{{year}}/{{month}}/{{day}}/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "BCMC Team"}
      - {label: "Date", name: "date", widget: "datetime", default: "post"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "categories", widget: "list"}
      - {label: "Teaser Text", name: "excerpt", widget: "text", required: true}
      - {label: "Body", name: "body", widget: "markdown"}