---
layout: null
---
backend:
  name: github
  repo: boxcritters/boxcrittersmods.ga
  base_url: https://api.boxcrittersmods.ga
media_folder: "uploads"
show_preview_links: true
publish_mode: editorial_workflow
logo_url: http://boxcrittersmods.ga/uploads/logo.png
collections:
{% for type in site.collections %}
  - name: '{{type.label }}'
    label: {{type.label| capitalize }}
    label_singular: {{type.label| capitalize }}
    media_folder: "/uploads/{{type.label }}/"
    folder: _{{type.label }}
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - label: "Author"
        name: "author"
        widget: "select"
        required: true
        multiple: true
        options: [{{site.authors|map:'title'|join:','}}]
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Date", name: "date", widget: "date", required: true}
      - {label: "Logo", name: "logo", widget: "image", required: false}
      - {label: "Banner", name: "image", widget: "image", required: false}
      - {label: "Texture Pack Code", name: "code", widget: "text", required: false}
      - {label: "Unfinished", name: "unfinished", widget: "boolean", required: false }
      - label: "Main Links"
        name: "primary"
        widget: "list"
        fields:
          - {label: "Link name", name: "name", widget: "string", required: true}
          - {label: "URL", name: "href", widget: "string", required: true}
      - label: "Other Links"
        name: "secondary"
        widget: "list"
        fields:
          - {label: "Link Name", name: "name", widget: "string", required: true}
          - {label: "URL", name: "href", widget: "string", required: true}
      - {label: "Show on Front Page", name: "featured", widget: "boolean", required: false}
      - {label: "Is a Userscript", name: "userscript", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Recommend", name: "recommend", widget: "boolean", required: false}
{% endfor %}