backend:
  name: github
  repo: boxcritters/boxcritters.github.io
  base_url: https://bc-mod-api.herokuapp.com
media_folder: "uploads"
collections:
  - name: 'texturepacks'
    label: Texture Packs
    folder: _texturepacks
    fields:
      - {label: "Title", name: "title", widget: "string"}